version: '3.1'
services:
  mariadb:
    image: mariadb:latest
    container_name: "mariadb"
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./etc/custom.cnf:/etc/mysql/my.cnf
      - ./var/lib/mysql:/var/lib/mysql
      - ./etc/conf.d:/etc/mysql/conf.d
      # 복사할 파일 : 가상머신 위치
    environment:
      - MYSQL_ROOT_PASSWORD=mariadb
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
      - TZ=Asia/Seoul
    command: mysqld --sql_mode="ORACLE"

  php:
    build:
      context: .
      dockerfile: Dockerfile.php
    container_name: "php"
    volumes:
      - .:/docker
      - ./etc/php.ini:/usr/local/etc/php/php.ini

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - 3333:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mariadb
      - PMA_PORT=3306

    depends_on:
      - mariadb
  nginx:
    image: nginx:1.19.7-alpine
    container_name: nginx_container
    volumes:
      - .:/docker
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./etc/nginx/logs:/etc/nginx/logs

    ports:
      - 80:80
      - 443:443
